feat(tasks):update and delete route
asGabriel/study-todo-project pull request #4
Opened 2024-04-19 00:04 UTC by asGabriel

implements the routes update and delete to task service.

2024-04-19 16:15 UTC, antoniomatiolijr requested changes

2024-04-19 16:15 UTC, antoniomatiolijr commented on src/repositories/task.ts
> +      "UPDATE TASKS SET TITLE=COALESCE($1, TITLE) WHERE ID=$2 RETURNING *",
não precisa do coalesce seguindo de que não pode estar vazio, uma outra coisa vc não controla isso via banco, vc controla nas camadas superiores sempre

2024-04-19 16:15 UTC, antoniomatiolijr commented on src/repositories/task.ts
> +      "UPDATE TASKS SET TITLE=COALESCE($1, TITLE) WHERE ID=$2 RETURNING *",
lembra de colocar uma checagem no handler dando um getTaskById para verificar se existe e não foi deltado antes de excluir

2024-04-21 23:34 UTC, asGabriel commented on src/domains/task.ts
> +export interface UpdateTaskDto {
Faz sentido mesmo, não tem porque ser opcional.

2024-04-21 23:44 UTC, asGabriel commented on src/repositories/task.ts
> +      "UPDATE TASKS SET TITLE=COALESCE($1, TITLE) WHERE ID=$2 RETURNING *",
Boa não me atentei, só coloquei a validação na rota de update.

2024-04-22 13:14 UTC, antoniomatiolijr requested changes

2024-04-22 13:14 UTC, antoniomatiolijr commented on src/handlers/task.ts
> +    if (!task) res.status(401).send("Task not found");
401 é not authorized

2024-04-22 13:14 UTC, antoniomatiolijr commented on src/handlers/task.ts
> +    );
e se o cara não mandar o título?

2024-04-22 13:14 UTC, antoniomatiolijr commented on src/repositories/task.ts
> +    return rows[0];
vc deveria receber tanto o title quanto o status, ou quebrar em duas funções

2024-04-23 00:08 UTC, asGabriel commented on src/handlers/task.ts
> +    if (!task) res.status(401).send("Task not found");
my bad

2024-04-23 00:41 UTC, asGabriel commented on src/handlers/task.ts
> +    );
criei um middleware que intercepta o body e valida se está vazio.

2024-04-23 00:50 UTC, asGabriel commented on src/handlers/task.ts
> +    );
mas tô analisando ele aqui a função dele é somente checar se o body não está vazio de fato... Nas aplicações que eu costumava fazer eu utilizava o class-validator pra ficar com essa responsa da validação dos DTOs

2024-04-23 08:51 UTC, asGabriel commented on src/repositories/task.ts
> +    return rows[0];
ok

2024-04-24 15:13 UTC, antoniomatiolijr requested changes

2024-04-24 15:13 UTC, antoniomatiolijr commented on src/handlers/task.ts
> +      res.status(400).send("Invalid status");
Manda uma mensagem mais clara

2024-04-24 15:13 UTC, antoniomatiolijr commented on src/handlers/task.ts
> +    );
vamos ter algo sobre nas próximas aulas, por momento vc pode só validar mesmo

2024-04-24 15:13 UTC, antoniomatiolijr commented on src/middlewares/bodyValidator.ts
> +  if (!req.body || Object.keys(req.body).length === 0) {
Podemos deixar isso mais legal.

Exemplo checar se o método da requisição é POST,PUT,PATCH e se é executar as regras. (assim vc não precisa adicionar na mão para as rotas put,patch,post), qualquer nova rota vai se beneficiar.


Uma outra coisa é garantir que delete, get não tenha body

2024-04-29 17:25 UTC, antoniomatiolijr commented on src/middlewares/bodyValidator.ts
> +  if (!req.body || Object.keys(req.body).length === 0) {
Eu tenho a solução já, que usa o conceito que vc construiu mas eu acho que é melhor resolver em um outro PR.

2024-04-29 17:25 UTC, antoniomatiolijr approved these changes

2024-04-29 17:25 UTC, merged